# Generated by Django 5.0.1 on 2024-02-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
