# Generated by Django 5.0.1 on 2024-02-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_cls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.IntegerField(blank=True, default=0, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
