# Generated by Django 5.0.1 on 2024-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='clas',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
