# Generated by Django 5.0.1 on 2024-02-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_attendence_clas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='clas',
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(blank=True, default=0, null=True)),
                ('hindi', models.IntegerField(blank=True, default=0, null=True)),
                ('urdu', models.IntegerField(blank=True, default=0, null=True)),
                ('physics', models.IntegerField(blank=True, default=0, null=True)),
                ('maths', models.IntegerField(blank=True, default=0, null=True)),
                ('chemistry', models.IntegerField(blank=True, default=0, null=True)),
                ('biology', models.IntegerField(blank=True, default=0, null=True)),
                ('computer', models.IntegerField(blank=True, default=0, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentresult', to='myapp.student')),
            ],
        ),
    ]
