from django.contrib import admin
from django.urls import path
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('home',views.home,name='home'),
    path('teacher', views.teacher, name='teacher'),
    path('administer',views.administer,name='administer'),
    path('student',views.student,name='student'),
    path('teacherframe',views.teacherframe,name='teacherframe'),
    path('studentframe',views.studentframe,name='studentframe'),
    path('adminframe',views.adminframe,name='adminframe'),
    path('addpuc1student',views.addpuc1student,name='addpuc1student'),
    path('postadd',views.postadd,name='postadd'),
    path('addstudent',views.addstudent,name="addstudent"),
    path('error',views.error,name='error'),
    path('view1',views.view1,name='view1'),
    path('view2',views.view2,name='view2'),
    path('fee1',views.fee1,name='fee1'),
    path('fee2',views.fee2,name='fee2'),
    path('stafform',views.stafform,name='stafform'),
    path('addstaff',views.addstaff,name='addstaff'),
    path('viewstaff',views.viewstaff,name='viewstaff'),
    path('staffsalary',views.staffsalary,name='staffsalary'),
    path('delete/<id>/',views.delete,name='delete'),
    path('update/<id>/',views.update,name='update'),
    path('delete_view2/<id>/',views.delete_view2,name='delete_view2'),
    path('update_view2/<id>/',views.update_view2,name='update_view2'),
    path('updatefee1/<id>/',views.updatefee1,name='updatefee1'),
    path('updatefee2/<id>/',views.updatefee2,name='updatefee2'),
    path('deletestaff/<id>/',views.deletestaff,name='deletestaff'),
    path('updatestaff/<id>/',views.updatestaff,name='updatestaff'),
    path('updatestaffee/<id>/',views.updatestaffee,name='updatestaffee'),
    path('updatestaff/<id>/viewstaff1',views.viewstaff1,name='viewstaff1'),
    path('updatestaffee/<id>/updatestaffee1',views.updatestaffee1,name='updatestaffee1'),
    path('update/<id>/back1',views.back1,name='back1'),
    path('update_view2/<id>/back2',views.back2,name='back2'),
    path('updatefee1/<id>/backfee1',views.backfee1,name='backfee1'),
    path('updatefee2/<id>/backfee1',views.backfee2,name='backfee2'),
    path('attendence1',views.attendence1,name='attendence1'),
    path('attendence2',views.attendence2,name='attendence2'),
    path('updateattendence1/<id>',views.updateattendence1,name='updateattendence1'),
    path('backatd1',views.attendenceback1,name='attendenceback1'),
    path('updateattendence2/<id>',views.updateattendence2,name='updateattendence2'),
    path('backatd2',views.attendenceback2,name='attendenceback2'),
    path('result1',views.result1,name='result1'),
    path('result2',views.result2,name='result2'),
    path('updatemarks1/<id>',views.updatemarks1,name='updatemarks1'),
    path('updatemarks2/<id>',views.updatemarks2,name='updatemarks2'),
    path('backre1',views.backre1,name='backre1'),
    path('backre2',views.backre2,name='backre2'),
    path('notice1',views.notice1,name='notice1'),
    path('notice2',views.notice2,name='notice2'),
    path('addnotice',views.addnotice,name='addnotice'),
    path('viewnotice',views.viewnotice,name='viewnotice'),
    path('noticeback1',views.noticeback1,name='noticeback1'),
    path('addnotice',views.addnotice,name='addnotice'),
    path('deletenotice/<id>',views.deletenotice,name='deletenotice'), 
    path('addnotice1',views.addnotice1,name='addnotice1'),
    path('viewnotice1',views.viewnotice1,name='viewnotice1'),
    path('deletenotice1/<id>',views.deletenotice1,name='deletenotice1'),
    path('stdatd1',views.stdatd1,name='stdatd1'),
    path('stdatd2',views.stdatd2,name='stdatd2'),
    path('stdre1',views.stdre1,name='stdre1'),
    path('stdre2',views.stdre2,name='stdre2'),
    path('stdnt1',views.stdnt1,name='stdnt1'),
    path('stdnt2',views.stdnt2,name='stdnt2'),
    path('teatd1',views.teatd1,name='teatd1'),
    path('teatd2',views.teatd2,name='teatd2'),
    path('updateteatd1/<id>',views.updateteatd1,name='updateteatd1'),
    path('updateteatd2/<id>',views.updateteatd2,name='updateteatd2'),
    path('backteatd1',views.backteatd1,name='backteatd1'),
    path('backteatd2',views.backteatd2,name='backteatd2'),
    path('tere1',views.tere1,name='tere1'),
    path('tere2',views.tere2,name='tere2'),
    path('updatetere1/<id>',views.updatetere1,name='updatetere1'),
    path('updatetere2/<id>',views.updatetere2,name='updatetere2'),
    path('backtere1',views.backtere1,name='backtere1'),
    path('backtere2',views.backtere2,name='backtere2'),
    path('tent1',views.tent1,name='tent1'),
    path('addtent1',views.addtent1,name='addtent1'),
    path('viewtent1',views.viewtent1,name='viewtent1'),
    path('deletetent1/<id>',views.deletetent1,name='deletetent1'),
    path('backtent1',views.backtent1,name='backtent1'),
    path('tent2',views.tent2,name='tent2'),
    path('addtent2',views.addtent2,name='addtent2'),
    path('viewtent2',views.viewtent2,name='viewtent2'),
    path('deletetent2/<id>',views.deletetent2,name='deletetent2'),
    path('backtent2',views.backtent2,name='backtent'),
    









] 
 


